//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714tfeller2h
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Reciepts = new HashSet<Reciept>();
        }
    
        public int Id { get; set; }
        public System.DateTime apptDate { get; set; }
        public decimal apptCost { get; set; }
    
        public virtual Person CustomerId { get; set; }
        public virtual Person PhotographerId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reciept> Reciepts { get; set; }
        public virtual Studio Studio { get; set; }
    }
}
